# Generated by Django 4.1.7 on 2023-04-14 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='isbn',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='books_read',
            field=models.CharField(blank=True, max_length=4000000, null=True),
        ),
    ]
