# Generated by Django 4.1.7 on 2023-04-15 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_review_isbn_alter_challenge_books_read'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='defaultImage',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='language',
            field=models.CharField(blank=True, choices=[('AR', 'Arabic'), ('EN', 'English'), ('FR', 'French')], default='EN', max_length=2, null=True),
        ),
    ]
