# Generated by Django 4.1.7 on 2023-03-23 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_product_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='brand',
            new_name='publisher',
        ),
        migrations.RemoveField(
            model_name='product',
            name='countInStock',
        ),
        migrations.AddField(
            model_name='product',
            name='available',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='language',
            field=models.CharField(blank=True, choices=[('AR', 'Arabic'), ('EN', 'English'), ('FR', 'French')], default='FR', max_length=2, null=True),
        ),
    ]
