# Generated by Django 4.1.7 on 2023-03-25 17:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_alter_book_description'),
        ('base', '0004_rename_brand_product_publisher_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='book',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='books.book'),
        ),
    ]
