# Generated by Django 4.1.7 on 2023-03-30 16:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_alter_book_description'),
        ('base', '0005_product_book'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='book',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='books.book'),
        ),
    ]
