# Generated by Django 4.1.7 on 2023-03-31 02:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_alter_product_book'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='book',
        ),
    ]
