# Generated by Django 4.1.7 on 2023-03-24 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isbn', models.CharField(blank=True, max_length=255)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('cover', models.ImageField(blank=True, default='/placeholder.png', null=True, upload_to='')),
                ('author', models.CharField(blank=True, max_length=255)),
                ('year', models.IntegerField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('num_pages', models.IntegerField(blank=True)),
            ],
        ),
    ]
